CREATE TABLE apex_030200.wwv_flow_toplevel_tabs (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  tab_set VARCHAR2(255 BYTE) NOT NULL,
  tab_sequence NUMBER NOT NULL,
  tab_name VARCHAR2(255 BYTE) NOT NULL,
  tab_image VARCHAR2(255 BYTE),
  tab_non_current_image VARCHAR2(255 BYTE),
  tab_image_attributes VARCHAR2(255 BYTE),
  tab_text VARCHAR2(2000 BYTE) NOT NULL,
  tab_target VARCHAR2(4000 BYTE) NOT NULL,
  display_condition VARCHAR2(4000 BYTE),
  display_condition2 VARCHAR2(4000 BYTE),
  display_condition_type VARCHAR2(255 BYTE),
  current_on_tabset VARCHAR2(255 BYTE),
  required_patch NUMBER,
  security_scheme VARCHAR2(255 BYTE),
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  tab_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_toplev_tab_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_toplev_tab_fk FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE
);