CREATE TABLE apex_030200.wwv_flow_list_items (
  "ID" NUMBER NOT NULL,
  list_id NUMBER,
  flow_id NUMBER,
  sub_item_count NUMBER,
  parent_list_item_id NUMBER,
  list_item_type VARCHAR2(255 BYTE) CONSTRAINT wwv_flows_val_listitemtype CHECK (list_item_type in ('LINK','FILE','TABLE')),
  list_item_status VARCHAR2(255 BYTE) CONSTRAINT wwv_flows_val_listitemstatus CHECK (list_item_status in ('PERSONAL','PUBLIC')),
  item_displayed VARCHAR2(255 BYTE) CONSTRAINT wwv_flow_val_listdisplayed CHECK (item_displayed in ('ON_DEMAND','ALWAYS','NEVER','BY_DEFAULT')),
  list_item_display_sequence NUMBER,
  list_item_link_text VARCHAR2(4000 BYTE),
  list_item_link_target VARCHAR2(4000 BYTE),
  list_item_icon VARCHAR2(4000 BYTE),
  list_item_icon_attributes VARCHAR2(4000 BYTE),
  list_item_icon_exp VARCHAR2(4000 BYTE),
  list_item_icon_exp_attr VARCHAR2(4000 BYTE),
  list_item_owner VARCHAR2(255 BYTE),
  list_item_current_for_pages VARCHAR2(4000 BYTE),
  list_item_current_type VARCHAR2(30 BYTE) CONSTRAINT wwv_flow_lst_curr_type_val CHECK (list_item_current_type in (
                                  'COLON_DELIMITED_PAGE_LIST',
                                  'PLSQL_EXPRESSION',
                                  'ALWAYS',
                                  'NEVER',
                                  'EXISTS',
                                  'NOT_EXISTS')),
  list_item_disp_cond_type VARCHAR2(255 BYTE),
  list_item_disp_condition VARCHAR2(4000 BYTE),
  list_item_disp_cond_type2 VARCHAR2(255 BYTE),
  list_item_disp_condition2 VARCHAR2(4000 BYTE),
  list_countclicks_y_n VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_list_count_chk CHECK (list_countclicks_y_n in ('Y','N')),
  list_countclicks_cat VARCHAR2(255 BYTE),
  list_text_01 VARCHAR2(4000 BYTE),
  list_text_02 VARCHAR2(4000 BYTE),
  list_text_03 VARCHAR2(4000 BYTE),
  list_text_04 VARCHAR2(4000 BYTE),
  list_text_05 VARCHAR2(4000 BYTE),
  list_text_06 VARCHAR2(4000 BYTE),
  list_text_07 VARCHAR2(4000 BYTE),
  list_text_08 VARCHAR2(4000 BYTE),
  list_text_09 VARCHAR2(4000 BYTE),
  list_text_10 VARCHAR2(4000 BYTE),
  list_text_11 VARCHAR2(4000 BYTE),
  list_text_12 VARCHAR2(4000 BYTE),
  list_text_13 VARCHAR2(4000 BYTE),
  list_text_14 VARCHAR2(4000 BYTE),
  list_text_15 VARCHAR2(4000 BYTE),
  list_text_16 VARCHAR2(4000 BYTE),
  list_text_17 VARCHAR2(4000 BYTE),
  list_text_18 VARCHAR2(4000 BYTE),
  list_text_19 VARCHAR2(4000 BYTE),
  list_text_20 VARCHAR2(4000 BYTE),
  required_patch NUMBER,
  security_scheme VARCHAR2(255 BYTE),
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  list_item_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_list_items_pk PRIMARY KEY ("ID"),
  CONSTRAINT parent_list_item_fk FOREIGN KEY (parent_list_item_id) REFERENCES apex_030200.wwv_flow_list_items ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_flow_list_items_fk FOREIGN KEY (list_id) REFERENCES apex_030200.wwv_flow_lists ("ID") ON DELETE CASCADE
);