CREATE TABLE apex_030200.wwv_mig_rpt_grp_dataitem (
  "ID" NUMBER NOT NULL,
  "GROUP_ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  itemid_readonly VARCHAR2(10 BYTE),
  "NAME" VARCHAR2(1000 BYTE),
  datatype VARCHAR2(10 BYTE) DEFAULT 'number' CONSTRAINT wwv_mig_grp_item_type CHECK (datatype in ('character','number',
                                                              'date','graphic',
                                                              'long','raw',
                                                              'longRaw','vchar2',
                                                              'vchar','rowid',
                                                              'mlabel','ref',
                                                              'object','collect',
                                                              'blob','clob',
                                                              'nclob','bfile','unknown' )),
  oracledatatype VARCHAR2(20 BYTE) DEFAULT 'character',
  javadatatype VARCHAR2(20 BYTE) DEFAULT 'null',
  width VARCHAR2(4000 BYTE) DEFAULT '10',
  columnorder VARCHAR2(1000 BYTE),
  "LABEL" VARCHAR2(4000 BYTE),
  defaultwidth VARCHAR2(4000 BYTE),
  defaultheight VARCHAR2(4000 BYTE),
  valueifnull VARCHAR2(4000 BYTE),
  inputmask VARCHAR2(4000 BYTE),
  sourcecolumn VARCHAR2(4000 BYTE),
  readfromfile VARCHAR2(3 BYTE) DEFAULT 'no' CONSTRAINT wwv_mig_grp_item_read CHECK (readfromfile in ('yes','no')),
  fileformat VARCHAR2(15 BYTE) DEFAULT 'text' CONSTRAINT wwv_mig_grp_fileformat CHECK (fileformat in ('text','image',
                                                               'CGM','OracleDrawing',
                                                               'OracleImage','sound',
                                                               'video','OLE2','imageURL')),
  breakorder VARCHAR2(10 BYTE) DEFAULT 'ascending' CONSTRAINT wwv_mig_grp_breakorder CHECK (breakorder in ('none','ascending','descending')),
  plsqlrefid_readonly VARCHAR2(4000 BYTE),
  columnflags VARCHAR2(4000 BYTE),
  defaultlabel VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CONSTRAINT wwv_mig_grpitem_sel_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_grp_dataitem_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_grp_dataitem_id_fk FOREIGN KEY ("GROUP_ID") REFERENCES apex_030200.wwv_mig_rpt_datasrc_grp ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_grp_item_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);