CREATE TABLE apex_030200.wwv_flow_popup_lov_template (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  flow_id NUMBER,
  popup_icon VARCHAR2(4000 BYTE) DEFAULT '#IMAGE_PREFIX#list.gif',
  popup_icon_attr VARCHAR2(4000 BYTE) DEFAULT 'width="13" height="13"',
  popup_icon2 VARCHAR2(4000 BYTE) DEFAULT null,
  popup_icon_attr2 VARCHAR2(4000 BYTE) DEFAULT null,
  page_name VARCHAR2(255 BYTE) DEFAULT 'winlov',
  page_title VARCHAR2(255 BYTE) DEFAULT 'Search Dialog',
  page_html_head VARCHAR2(4000 BYTE) DEFAULT '<link rel="stylesheet" href="#IMAGE_PREFIX#platform2.css" type="text/css">',
  page_body_attr VARCHAR2(255 BYTE) DEFAULT 'bgcolor="white" OnLoad="first_field()"',
  before_field_text VARCHAR2(4000 BYTE) DEFAULT ' ',
  after_field_text VARCHAR2(4000 BYTE) DEFAULT '</div><br />',
  page_heading_text VARCHAR2(4000 BYTE) DEFAULT '<link rel="stylesheet" href="#IMAGE_PREFIX#platform2.css" type="text/css"><style>a:link { color:#336699; text-decoration:none; padding:2px;} a:visited { color:#336699; text-decoration:none;} a:hover { color:red; text-decoration:underline;} body { font-family:arial; background-color:#ffffff;} </style>',
  page_footer_text VARCHAR2(4000 BYTE) DEFAULT '</center></td></tr></table>',
  before_result_set VARCHAR2(4000 BYTE) DEFAULT '',
  after_result_set VARCHAR2(4000 BYTE) DEFAULT '',
  filter_width VARCHAR2(255 BYTE) DEFAULT '20',
  filter_max_width VARCHAR2(255 BYTE) DEFAULT '100',
  filter_text_attr VARCHAR2(4000 BYTE) DEFAULT null,
  find_button_text VARCHAR2(255 BYTE) DEFAULT 'Search',
  find_button_image VARCHAR2(255 BYTE) DEFAULT null,
  find_button_attr VARCHAR2(4000 BYTE) DEFAULT '',
  close_button_text VARCHAR2(255 BYTE) DEFAULT 'Close',
  close_button_image VARCHAR2(255 BYTE) DEFAULT null,
  close_button_attr VARCHAR2(4000 BYTE) DEFAULT '',
  next_button_text VARCHAR2(255 BYTE) DEFAULT 'Next',
  next_button_image VARCHAR2(255 BYTE) DEFAULT null,
  next_button_attr VARCHAR2(4000 BYTE) DEFAULT '',
  prev_button_text VARCHAR2(255 BYTE) DEFAULT 'Previous',
  prev_button_image VARCHAR2(255 BYTE) DEFAULT null,
  prev_button_attr VARCHAR2(4000 BYTE) DEFAULT '',
  scrollbars VARCHAR2(255 BYTE) DEFAULT '1',
  resizable VARCHAR2(255 BYTE) DEFAULT '1',
  width VARCHAR2(255 BYTE) DEFAULT '400',
  height VARCHAR2(255 BYTE) DEFAULT '450',
  result_row_x_of_y VARCHAR2(255 BYTE) DEFAULT 'Row(s) #FIRST_ROW# - #LAST_ROW',
  result_rows_per_pg NUMBER DEFAULT 10,
  when_no_data_found_message VARCHAR2(4000 BYTE),
  before_first_fetch_message VARCHAR2(4000 BYTE),
  minimum_characters_required NUMBER,
  theme_id NUMBER,
  theme_class_id NUMBER,
  reference_id NUMBER,
  last_updated_on DATE,
  last_updated_by VARCHAR2(255 BYTE),
  translate_this_template VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_popup_trans_temp CHECK (translate_this_template in ('Y','N')),
  template_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_pk_poplov_temp PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_fk_poplov_temp FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE
);