CREATE TABLE apex_030200.wwv_flow_list_templates (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  list_template_name VARCHAR2(255 BYTE) NOT NULL,
  list_template_current CLOB,
  list_template_noncurrent CLOB,
  list_template_before_rows VARCHAR2(4000 BYTE),
  list_template_after_rows VARCHAR2(4000 BYTE),
  between_items VARCHAR2(4000 BYTE),
  before_sub_list VARCHAR2(4000 BYTE),
  after_sub_list VARCHAR2(4000 BYTE),
  between_sub_list_items VARCHAR2(4000 BYTE),
  sub_list_item_current CLOB,
  sub_list_item_noncurrent CLOB,
  item_template_curr_w_child CLOB,
  item_template_noncurr_w_child CLOB,
  sub_template_curr_w_child CLOB,
  sub_template_noncurr_w_child CLOB,
  reference_id NUMBER,
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  theme_id NUMBER,
  theme_class_id NUMBER,
  translate_this_template VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_list_trans_temp CHECK (translate_this_template in ('Y','N')),
  list_template_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_list_template_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_list_template_fk FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE
);