CREATE TABLE apex_030200.wwv_mig_frm_report (
  "ID" NUMBER NOT NULL,
  formmodule_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  commmode VARCHAR2(4000 BYTE),
  datasourceblock VARCHAR2(4000 BYTE),
  dirtyinfo VARCHAR2(4000 BYTE),
  executemode VARCHAR2(4000 BYTE),
  filename VARCHAR2(4000 BYTE),
  "NAME" VARCHAR2(4000 BYTE),
  parentfilename VARCHAR2(4000 BYTE),
  parentfilepath VARCHAR2(4000 BYTE),
  parentmodule VARCHAR2(4000 BYTE),
  parentmoduletype VARCHAR2(4000 BYTE),
  parentname VARCHAR2(4000 BYTE),
  parenttype VARCHAR2(4000 BYTE),
  persistentclientinfolength VARCHAR2(4000 BYTE),
  queryname VARCHAR2(4000 BYTE),
  report_comment CLOB,
  reportdestinationformat VARCHAR2(4000 BYTE),
  reportdestinationname VARCHAR2(4000 BYTE),
  reportdestinationtype VARCHAR2(4000 BYTE),
  reportparameters VARCHAR2(4000 BYTE),
  reportserver VARCHAR2(4000 BYTE),
  smartclass VARCHAR2(4000 BYTE),
  subclassobjectgroup VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CONSTRAINT wwv_mig_frm_report_sel_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'N',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'Y',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_frm_report_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_frm_rpt_frmmdl_id_fk FOREIGN KEY (formmodule_id) REFERENCES apex_030200.wwv_mig_frm_formmodules ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_frm_rpt_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);