CREATE TABLE apex_030200.wwv_flow_templates (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE),
  look NUMBER,
  header_template CLOB,
  footer_template CLOB,
  success_message VARCHAR2(4000 BYTE),
  current_tab VARCHAR2(4000 BYTE),
  current_tab_font_attr VARCHAR2(255 BYTE),
  non_current_tab VARCHAR2(4000 BYTE),
  non_current_tab_font_attr VARCHAR2(255 BYTE),
  current_image_tab VARCHAR2(4000 BYTE),
  non_current_image_tab VARCHAR2(4000 BYTE),
  top_current_tab VARCHAR2(4000 BYTE),
  top_current_tab_font_attr VARCHAR2(255 BYTE),
  top_non_current_tab VARCHAR2(4000 BYTE),
  top_non_current_tab_font_attr VARCHAR2(255 BYTE),
  box CLOB,
  navigation_bar VARCHAR2(4000 BYTE),
  navbar_entry VARCHAR2(4000 BYTE),
  body_title VARCHAR2(4000 BYTE),
  message VARCHAR2(4000 BYTE),
  attribute1 VARCHAR2(4000 BYTE),
  attribute2 VARCHAR2(4000 BYTE),
  attribute3 VARCHAR2(4000 BYTE),
  attribute4 VARCHAR2(4000 BYTE),
  attribute5 VARCHAR2(4000 BYTE),
  attribute6 VARCHAR2(4000 BYTE),
  default_button_position VARCHAR2(30 BYTE),
  table_bgcolor VARCHAR2(255 BYTE),
  heading_bgcolor VARCHAR2(255 BYTE),
  table_cattributes VARCHAR2(255 BYTE),
  font_size VARCHAR2(255 BYTE),
  font_face VARCHAR2(255 BYTE),
  region_table_cattributes VARCHAR2(255 BYTE),
  app_tab_before_tabs VARCHAR2(4000 BYTE),
  app_tab_current_tab VARCHAR2(4000 BYTE),
  app_tab_non_current_tab VARCHAR2(4000 BYTE),
  app_tab_after_tabs VARCHAR2(4000 BYTE),
  error_page_template VARCHAR2(4000 BYTE),
  reference_id NUMBER,
  breadcrumb_def_reg_pos VARCHAR2(255 BYTE),
  sidebar_def_reg_pos VARCHAR2(255 BYTE),
  required_patch NUMBER,
  security_group_id NUMBER NOT NULL,
  theme_id NUMBER,
  theme_class_id NUMBER,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  translate_this_template VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_trans_temp CHECK (translate_this_template in ('Y','N')),
  template_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_templates_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_templates_fk FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE
);