CREATE TABLE apex_030200.wwv_flow_job_bind_values (
  "JOB" NUMBER NOT NULL,
  "NAME" VARCHAR2(200 BYTE) NOT NULL,
  "VALUE" VARCHAR2(3125 BYTE),
  PRIMARY KEY ("JOB","NAME")
)
ORGANIZATION INDEX OVERFLOW;