CREATE TABLE apex_030200.wwv_mig_forms (
  "ID" NUMBER NOT NULL,
  project_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  description VARCHAR2(4000 BYTE),
  file_name VARCHAR2(255 BYTE),
  file_mime_type VARCHAR2(255 BYTE),
  file_content BLOB,
  xml_content XMLTYPE,
  file_char_set VARCHAR2(255 BYTE),
  file_updated_on DATE,
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CONSTRAINT wwv_mig_frm_select_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_forms_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_forms_uk UNIQUE (file_name,project_id),
  CONSTRAINT wwv_mig_forms_project_id_fk FOREIGN KEY (project_id) REFERENCES apex_030200.wwv_mig_projects ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_forms_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);