CREATE TABLE apex_030200.wwv_mig_olb_olt_menu_menuitem (
  "ID" NUMBER NOT NULL,
  menu_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  "NAME" VARCHAR2(4000 BYTE),
  magicitem VARCHAR2(4000 BYTE),
  "LABEL" VARCHAR2(4000 BYTE),
  menuitemtype VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CONSTRAINT wwv_mig_olb_olt_mmi_sel_f_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_olb_olt_menu_mitem_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_olb_olt_mmi_menu_id_fk FOREIGN KEY (menu_id) REFERENCES apex_030200.wwv_mig_olb_olt_menu ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_olb_olt_mmi_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);