CREATE TABLE apex_030200.wwv_flow_step_items (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  flow_step_id NUMBER,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  name_length NUMBER,
  data_type VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_datatype CHECK (data_type in (
                      		'VARCHAR',
                      		'NUMBER',
                      		'DATE')),
  accept_processing VARCHAR2(30 BYTE) CONSTRAINT wwv_valid_fsitem_accpproc CHECK (accept_processing in (
                      		'REPLACE_EXISTING',
                      		'REPLACE_NULL_VALUES',
                      		'RAISE_ERROR_ON_REPLACE',
                      		'ADD_TO_EXISTING')),
  item_sequence NUMBER,
  item_plug_id NUMBER,
  use_cache_before_default VARCHAR2(30 BYTE) CONSTRAINT wwv_valid_fsitem_usecache CHECK (use_cache_before_default in (
                      		'YES',
                      		'NO')),
  item_default VARCHAR2(4000 BYTE),
  item_default_type VARCHAR2(255 BYTE) CONSTRAINT wwv_valid_fsitem_idt CHECK (item_default_type in (
                      		'STATIC_TEXT_WITH_SUBSTITUTIONS',
                      		'PLSQL_FUNCTION_BODY',
                      		'PLSQL_EXPRESSION',
                      		'SQL_QUERY')),
  prompt VARCHAR2(4000 BYTE),
  pre_element_text VARCHAR2(4000 BYTE),
  post_element_text VARCHAR2(4000 BYTE),
  format_mask VARCHAR2(255 BYTE),
  item_field_template NUMBER,
  "SOURCE" VARCHAR2(4000 BYTE),
  source_type VARCHAR2(30 BYTE) CONSTRAINT wwv_valid_fsitem_sourcetype CHECK (source_type in (
                      		'PREFERENCE',
                      		'ALWAYS_NULL',
                      		'STATIC',
                      		'QUERY',
                      		'ITEM',
                      		'FUNCTION',
                      		'FUNCTION_BODY',
                      		'DB_COLUMN',
                      		'PLSQL_ANONYMOUS_BLOCK')),
  source_post_computation VARCHAR2(4000 BYTE),
  display_as VARCHAR2(50 BYTE) CONSTRAINT wwv_valid_fsitem_displayas CHECK (display_as in (
                                'DISPLAY_ONLY_PLSQL',
                                'FILE',
                                'BUTTON',
                                'HIDDEN',
                                'HIDDEN_PROTECTED',
                                'DISPLAY_ONLY_HTML',
                                'STOP_AND_START_HTML_TABLE',
                                'DISPLAY_ONLY_ESCAPE_SC',
                                'IMAGE',
                                'DISPLAY_AND_SAVE',
                                'DISPLAY_AND_SAVE_LOV',
                                'CHECKBOX',
                                'POPUP',
                                'POPUP_FILTER',
                                'POPUP2',
                                'POPUP3',
                                'POPUP4',
                                'POPUP5',
                                'POPUP6',
                                'POPUP_KEY_LOV',
                                'POPUP_KEY_LOV_NOFETCH',
                                'POPUP_COLOR',
                                'PICK_DATE_USING_FLOW_FORMAT_MASK',
                                'PICK_DATE_USING_APP_FORMAT_MASK',
                                'PICK_DATE_USING_APP_DATE_FORMAT',
                                'PICK_DATE_USING_FORMAT_MASK',
                                'PICK_DATE_DD_MON_RR',
                                'PICK_DATE_DD_MON_RR_HH_MI',
                                'PICK_DATE_DD_MON_RR_HH24_MI',
                                'PICK_DATE_DD_MON_YYYY',
                                'PICK_DATE_DD_MON_YYYY_HH_MI',
                                'PICK_DATE_DD_MON_YYYY_HH24_MI',
                                'PICK_DATE_DD_MM_YYYY',
                                'PICK_DATE_DD_MM_YYYY_HH_MI',
                                'PICK_DATE_DD_MM_YYYY_HH24_MI',
                                'PICK_DATE_MM_DD_YYYY',
                                'PICK_DATE_MM_DD_YYYY_HH_MI',
                                'PICK_DATE_MM_DD_YYYY_HH24_MI',
                                'PICK_DATE_DD_MON_YY',
                                'PICK_DATE_DD_MON_YY_HH_MI',
                                'PICK_DATE_DD_MON_YY_HH24_MI',
                                'PICK_DATE_YYYY_MM_DD',
                                'PICK_DATE_YYYY_MM_DD_HH_MI',
                                'PICK_DATE_YYYY_MM_DD_HH24_MI',
                                'PICK_DATE_RR_MON_DD',
                                'PICK_DATE_RR_MON_DD_HH_MI',
                                'PICK_DATE_RR_MON_DD_HH24_MI',
                                'PICK_DATE_DD_MM_YYYY_DASH',
                                'PICK_DATE_DD_MM_YYYY_HH_MI_DASH',
                                'PICK_DATE_DD_MM_YYYY_HH24_MI_DASH',
                                'PICK_DATE_DD_MM_YYYY_DOT',
                                'PICK_DATE_DD_MM_YYYY_HH_MI_DOT',
                                'PICK_DATE_DD_MM_YYYY_HH24_MI_DOT',
                                'PICK_DATE_YYYY_DD_MM_DOT',
                                'PICK_DATE_YYYY_DD_MM_HH_MI_DOT',
                                'PICK_DATE_YYYY_DD_MM_HH24_MI_DOT',
                                'PICK_DATE_YYYY_MM_DD_SLASH',
                                'PICK_DATE_YYYY_MM_DD_HH_MI_SLASH',
                                'PICK_DATE_YYYY_MM_DD_HH24_MI_SLASH',
                                'DISPLAY_ONLY_LOV',
                                'COMBOBOX',
                                'SHOW_AS_SL_WITH_POPUP',
                                'COMBOBOX_WITH_URL_REDIRECT',
                                'COMBOBOX_WITH_BRANCH_TO_PAGE',
                                'COMBOBOX_WITH_SUBMIT',
                                'COMBOBOX_WITH_JS_POST',
                                'COMBOBOX_WITH_JS_REDIRECT',
                                'MULTIPLESELECT',
                                'SHUTTLE',
                                'RADIOGROUP',
                                'RADIOGROUP2',
                                'RADIOGROUP_WITH_REDIRECT',
                                'RADIOGROUP_WITH_SUBMIT',
                                'RADIOGROUP_WITH_JS_SUBMIT',
                                'TEXTAREA',
                                'TEXTAREA_WITH_SPELL_CHECK',
                                'TEXTAREA-AUTO-HEIGHT',
                                'TEXTAREA_WITH_CONTROLS',
                                'TEXTAREA_WITH_HTML_EDITOR_BASIC',
                                'TEXTAREA_WITH_HTML_EDITOR_STANDARD',
                                'TEXTAREA_CHAR_COUNT',
                                'TEXTAREA_CHAR_COUNT_SPELL',
                                'TEXT',
                                'TEXT_WITH_ENTER_SUBMIT',
                                'TEXT_DISABLED',
                                'TEXT_DISABLED_AND_SAVE',
                                'TEXT_WITH_CALCULATOR',
                                'PASSWORD',
                                'PASSWORD_WITH_ENTER_SUBMIT',
                                'PASSWORD_DNSS',
                                'PASSWORD_WITH_SUBMIT_DNSS',
                                'LIST_MGR',
                                'LIST_MGR2',
                                'LIST_MGR3',
                                'LIST_MGR_VIEW',
                                'LIST_MGR_VIEW2'
                                )),
  read_only_when VARCHAR2(4000 BYTE),
  read_only_when2 VARCHAR2(4000 BYTE),
  read_only_when_type VARCHAR2(255 BYTE),
  read_only_disp_attr VARCHAR2(4000 BYTE),
  named_lov VARCHAR2(255 BYTE),
  lov VARCHAR2(4000 BYTE),
  lov_columns NUMBER,
  lov_display_extra VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_lovextra CHECK (lov_display_extra in (
                      		'YES',
                      		'NO')),
  lov_display_null VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_lovdispnull CHECK (lov_display_null in (
                      		'YES',
                      		'NO')),
  lov_null_text VARCHAR2(255 BYTE),
  lov_null_value VARCHAR2(255 BYTE),
  lov_translated VARCHAR2(1 BYTE) CONSTRAINT wwv_valid_lov_trans CHECK (lov_translated in ('Y','N',null)),
  csize NUMBER,
  cmaxlength NUMBER,
  cheight NUMBER,
  cattributes VARCHAR2(2000 BYTE),
  cattributes_element VARCHAR2(4000 BYTE),
  tag_attributes VARCHAR2(2000 BYTE),
  tag_attributes2 VARCHAR2(4000 BYTE),
  button_image VARCHAR2(255 BYTE),
  button_image_attr VARCHAR2(255 BYTE),
  begin_on_new_line VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_beginonnewline CHECK (begin_on_new_line in (
                      		'YES',
                      		'NO')),
  begin_on_new_field VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_beginonnewfield CHECK (begin_on_new_field in (
                      		'YES',
                      		'NO')),
  colspan NUMBER,
  rowspan NUMBER,
  label_alignment VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_labelalign CHECK (label_alignment in (
                      		'LEFT',
                      		'RIGHT',
                      		'CENTER',
                      		'ABOVE',
                      		'BELOW',
                      		'LEFT-TOP',
                      		'RIGHT-TOP',
                      		'CENTER-TOP',
                      		'LEFT-BOTTOM',
                      		'RIGHT-BOTTOM',
                      		'CENTER-BOTTOM',
                      		'LEFT-CENTER',
                      		'RIGHT-CENTER',
                      		'CENTER-CENTER'
                      		)),
  field_alignment VARCHAR2(30 BYTE) CONSTRAINT valid_fsitem_fieldalign CHECK (field_alignment in (
                      		'LEFT',
                      		'RIGHT',
                      		'CENTER',
                      		'LEFT-TOP',
                      		'RIGHT-TOP',
                      		'CENTER-TOP',
                      		'LEFT-BOTTOM',
                      		'RIGHT-BOTTOM',
                      		'CENTER-BOTTOM',
                      		'LEFT-CENTER',
                      		'RIGHT-CENTER',
                      		'CENTER-CENTER'
                      		)),
  field_template NUMBER,
  label_cell_attr VARCHAR2(4000 BYTE),
  field_cell_attr VARCHAR2(4000 BYTE),
  display_when VARCHAR2(4000 BYTE),
  display_when2 VARCHAR2(4000 BYTE),
  display_when_type VARCHAR2(255 BYTE),
  is_persistent VARCHAR2(1 BYTE) CONSTRAINT valid_fsitem_ispersistent CHECK (is_Persistent in ('Y','N','U')),
  protection_level VARCHAR2(1 BYTE) CONSTRAINT valid_fsitem_protection_level CHECK (protection_level in ('N','B','P','S','I')),
  escape_on_http_input VARCHAR2(1 BYTE) CONSTRAINT valfsitem_escape_on_http_input CHECK (escape_on_http_input in ('Y','N')),
  security_scheme VARCHAR2(255 BYTE),
  required_patch NUMBER,
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  encrypt_session_state_yn VARCHAR2(1 BYTE),
  item_comment VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_step_items_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_step_items_fk FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_flow_step_items_fk2 FOREIGN KEY (flow_id,flow_step_id) REFERENCES apex_030200.wwv_flow_steps (flow_id,"ID") ON DELETE CASCADE
);