CREATE TABLE apex_030200.wwv_mig_acc_forms_controls (
  "ID" NUMBER NOT NULL,
  project_id NUMBER,
  security_group_id NUMBER,
  dbid NUMBER NOT NULL,
  formid NUMBER(11),
  controlid NUMBER(11) NOT NULL,
  controlname VARCHAR2(400 BYTE),
  controltype NUMBER(11),
  eventprocprefix VARCHAR2(4000 BYTE),
  inselection NUMBER(11),
  "LEFT" NUMBER,
  "PARENT" VARCHAR2(4000 BYTE),
  section NUMBER(11),
  "TAG" VARCHAR2(4000 BYTE),
  top NUMBER(11),
  "VISIBLE" NUMBER(1),
  backcolor NUMBER(11),
  backstyle NUMBER(11),
  boundcolumn NUMBER,
  ctrlcaption VARCHAR2(4000 BYTE),
  columncount NUMBER,
  columnheads VARCHAR2(4000 BYTE),
  columnwidths VARCHAR2(4000 BYTE),
  controlsource VARCHAR2(4000 BYTE),
  controltiptext VARCHAR2(4000 BYTE),
  defaultvalue VARCHAR2(4000 BYTE),
  displaywhen NUMBER(11),
  enabled NUMBER(1),
  fontbold NUMBER(11),
  fontitalic NUMBER(11),
  fontname VARCHAR2(1000 BYTE),
  fontsize NUMBER(11),
  fontunderline NUMBER(1),
  fontwheight NUMBER,
  forecolor NUMBER,
  "FORMAT" VARCHAR2(4000 BYTE),
  height NUMBER(11),
  helpcontextid NUMBER(11),
  limittolist NUMBER(11),
  linkchildfields VARCHAR2(4000 BYTE),
  linkmasterfields VARCHAR2(4000 BYTE),
  listrows NUMBER,
  multirow NUMBER(11),
  onchange VARCHAR2(4000 BYTE),
  onclick VARCHAR2(4000 BYTE),
  ondblclick VARCHAR2(4000 BYTE),
  onkeydown VARCHAR2(4000 BYTE),
  onkeypress VARCHAR2(4000 BYTE),
  onkeyup VARCHAR2(4000 BYTE),
  onmousedown VARCHAR2(4000 BYTE),
  onmousemove VARCHAR2(4000 BYTE),
  onmouseup VARCHAR2(4000 BYTE),
  optionvalue NUMBER,
  pageindex NUMBER,
  picture VARCHAR2(4000 BYTE),
  picturealignment NUMBER,
  pictureresizemode NUMBER,
  picturetiling NUMBER,
  picturetype NUMBER,
  rowsource VARCHAR2(4000 BYTE),
  rowsourcetype VARCHAR2(4000 BYTE),
  shortcutmenubar VARCHAR2(4000 BYTE),
  sourceobject VARCHAR2(4000 BYTE),
  statusbartext VARCHAR2(4000 BYTE),
  style NUMBER,
  tabfixedheight NUMBER(11),
  tabfixedwidth NUMBER(11),
  tabindex NUMBER(11),
  tabstop NUMBER(11),
  textalign NUMBER(11),
  textfontcharset NUMBER(11),
  width NUMBER(11),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_frms_ctl_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_acc_frm_ctl_fk FOREIGN KEY (project_id,dbid,formid) REFERENCES apex_030200.wwv_mig_acc_forms (project_id,dbid,formid) ON DELETE CASCADE
);