CREATE TABLE apex_030200.wwv_mig_rpt_grp_summary (
  "ID" NUMBER NOT NULL,
  "GROUP_ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  "NAME" VARCHAR2(4000 BYTE),
  "SOURCE" VARCHAR2(4000 BYTE),
  "FUNCTION" VARCHAR2(15 BYTE) DEFAULT 'sum' CONSTRAINT wwv_mig_grp_sum_func CHECK ("FUNCTION" in ('sum','average','median',
                                                              'minimum','maximum','count',
                                                              'first','last','percentOfTotal',
                                                              'percentile','stdDeviation','variance')),
  width VARCHAR2(4000 BYTE) DEFAULT '10',
  "SCALE" VARCHAR2(4000 BYTE) DEFAULT '0',
  "PRECISION" VARCHAR2(4000 BYTE) DEFAULT '0',
  "COMPUTE" VARCHAR2(4000 BYTE),
  "RESET" VARCHAR2(4000 BYTE),
  productorder VARCHAR2(4000 BYTE),
  valueifnull VARCHAR2(4000 BYTE),
  readfromfile VARCHAR2(3 BYTE) DEFAULT 'no' CONSTRAINT wwv_mig_grp_sum_read CHECK (readfromfile in ('yes','no')),
  fileformat VARCHAR2(15 BYTE) DEFAULT 'text' CONSTRAINT wwv_mig_grp_sum_format CHECK (fileformat in ('text','image','CGM',
                                                                'OracleDrawing','OracleImage',
                                                                'sound','video','OLE2','imageURL')),
  nullval VARCHAR2(4000 BYTE),
  defaultwidth VARCHAR2(4000 BYTE),
  defaultheight VARCHAR2(4000 BYTE),
  columnflags VARCHAR2(4000 BYTE),
  defaultlabel VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CONSTRAINT wwv_mig_grpsum_sel_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_grp_sum_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_grp_sum_id_fk FOREIGN KEY ("GROUP_ID") REFERENCES apex_030200.wwv_mig_rpt_datasrc_grp ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_grp_sum_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);