CREATE TABLE apex_030200.wwv_flow_page_plugs (
  "ID" NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  page_id NUMBER,
  plug_name VARCHAR2(255 BYTE) NOT NULL,
  region_name VARCHAR2(255 BYTE),
  plug_template NUMBER,
  plug_display_sequence NUMBER NOT NULL,
  plug_display_column NUMBER CONSTRAINT wwv_valid_plug_disp_column CHECK (plug_display_column in (1,2,3,4,5,6,7,8,9)),
  plug_display_point VARCHAR2(255 BYTE) CONSTRAINT wwv_valid_plug_disppoint CHECK (plug_display_point in (
                                 'REGION_POSITION_01',
                                 'REGION_POSITION_02',
                                 'REGION_POSITION_03',
                                 'REGION_POSITION_04',
                                 'REGION_POSITION_05',
                                 'REGION_POSITION_06',
                                 'REGION_POSITION_07',
                                 'REGION_POSITION_08',
                                 'REGION_POSITION_09',
                                 'REGION_POSITION_10',
                                 'REGION_POSITION_11',
                                 'REGION_POSITION_12',
                                 'REGION_POSITION_13',
                                 'REGION_POSITION_14',
                                 'REGION_POSITION_15',
                                 'REGION_POSITION_16',
                                 'REGION_POSITION_17',
                                 'REGION_POSITION_18',
                                 'REGION_POSITION_19',
                                 'REGION_POSITION_20',
                                 'REGION_POSITION_21',
                                 'REGION_POSITION_22',
                                 'REGION_POSITION_23',
                                 'REGION_POSITION_24',
                                 'REGION_POSITION_25',
                                 'REGION_POSITION_26',
                                 'REGION_POSITION_27',
                                 'REGION_POSITION_28',
                                 'REGION_POSITION_29',
                                 'REGION_POSITION_30',
                                 'AFTER_HEADER',
                                 'BEFORE_BOX_BODY',
                                 'BEFORE_SHOW_ITEMS',
                                 'AFTER_SHOW_ITEMS',
                                 'BEFORE_FOOTER')),
  plug_source CLOB,
  menu_template_id NUMBER,
  list_template_id NUMBER,
  plug_source_type VARCHAR2(255 BYTE),
  plug_display_error_message VARCHAR2(4000 BYTE),
  plug_required_role VARCHAR2(255 BYTE),
  plug_display_when_condition VARCHAR2(4000 BYTE),
  plug_display_when_cond2 VARCHAR2(4000 BYTE),
  plug_display_condition_type VARCHAR2(255 BYTE),
  plug_header VARCHAR2(4000 BYTE),
  plug_footer VARCHAR2(4000 BYTE),
  plug_query_row_template NUMBER,
  plug_query_headings VARCHAR2(4000 BYTE),
  plug_query_headings_type VARCHAR2(255 BYTE) CONSTRAINT wwv_plug_head_type_check CHECK (plug_query_headings_type in (
                                 'NO_HEADINGS',
                                 'SORT_ENABLED_COLON_DELMITED_LIST',
                                 'SORT_ENABLED_QUERY_COLUMNS',
                                 'SORT_ENABLED_QUERY_COLUMNS_INITCAP',
                                 'COLON_DELMITED_LIST',
                                 'COLON_DELIMITED_LIST',
                                 'PIPE_DELMITED_LIST',
                                 'BACKSLASH_DELMITED_LIST',
                                 'QUERY_COLUMNS',
                                 'QUERY_COLUMNS_INITCAP',
                                 'FUNCTION_BODY_RETURNING_COLON_DELIMITED_LIST',
                                 'FUNCTION_BODY_RETURNING_PIPE_DELIMITED_LIST')),
  plug_query_num_rows NUMBER,
  plug_query_num_rows_type VARCHAR2(255 BYTE) CONSTRAINT wwv_plug_query_num_rows_type CHECK (plug_query_num_rows_type in (
                                 'NEXT_PREVIOUS_LINKS',
                                 'COMPUTED_BUT_NOT_DISPLAYED',
                                 'ROW_RANGES',
                                 'ROW_RANGES_RIGHT',
                                 'ROW_RANGES_WITH_LINKS_RIGHT',
                                 'ROW_RANGES_WITH_LINKS',
                                 'ROW_RANGES_IN_SELECT_LIST',
                                 'ROW_RANGES_IN_SELECT_LIST_RIGHT',
                                 'ROWS_PER_PAGE_FROM_ITEM',
                                 'ROWS_X_TO_Y_OF_Z',
                                 'ROWS_X_TO_Y',
                                 'SEARCH_ENGINE',
                                 'SEARCH_ENGINE_RIGHT',
                                 '0'
                                 )),
  pagination_display_position VARCHAR2(255 BYTE),
  ajax_enabled VARCHAR2(1 BYTE),
  plug_query_num_rows_item VARCHAR2(255 BYTE),
  plug_query_no_data_found VARCHAR2(4000 BYTE),
  plug_query_more_data VARCHAR2(4000 BYTE),
  plug_query_row_count_max NUMBER,
  plug_query_format_out VARCHAR2(255 BYTE),
  plug_query_show_nulls_as VARCHAR2(255 BYTE),
  plug_query_col_allignments VARCHAR2(255 BYTE),
  plug_query_break_cols VARCHAR2(255 BYTE),
  plug_query_sum_cols VARCHAR2(255 BYTE),
  plug_query_number_formats VARCHAR2(4000 BYTE),
  plug_query_table_border VARCHAR2(255 BYTE),
  plug_query_hit_highlighting VARCHAR2(4000 BYTE),
  plug_query_asc_image VARCHAR2(4000 BYTE),
  plug_query_asc_image_attr VARCHAR2(4000 BYTE),
  plug_query_desc_image VARCHAR2(4000 BYTE),
  plug_query_desc_image_attr VARCHAR2(4000 BYTE),
  plug_query_exp_filename VARCHAR2(255 BYTE),
  plug_query_exp_separator VARCHAR2(1 BYTE),
  plug_query_exp_enclosed_by VARCHAR2(1 BYTE),
  plug_query_strip_html VARCHAR2(1 BYTE) CONSTRAINT wwv_plug_strip_html CHECK (plug_query_strip_html in ('Y','N')),
  plug_query_options VARCHAR2(4000 BYTE),
  plug_query_max_columns NUMBER,
  plug_column_width VARCHAR2(255 BYTE),
  plug_customized VARCHAR2(255 BYTE),
  plug_customized_name VARCHAR2(4000 BYTE),
  plug_override_reg_pos VARCHAR2(255 BYTE),
  required_patch NUMBER,
  plug_url_text_begin VARCHAR2(4000 BYTE),
  plug_url_text_end VARCHAR2(4000 BYTE),
  plug_caching VARCHAR2(255 BYTE) CONSTRAINT wwv_plug_valid_caching CHECK (plug_caching in (
                                 'NOT_CACHED',
                                 'CACHED',
                                 'CACHED_BY_USER',
                                 'CACHED_BY_USER_AND_SESSION')),
  plug_cache_when VARCHAR2(255 BYTE),
  plug_cache_expression1 VARCHAR2(4000 BYTE),
  plug_cache_expression2 VARCHAR2(4000 BYTE),
  plug_caching_session_state VARCHAR2(4000 BYTE),
  plug_caching_max_age_in_sec NUMBER,
  plug_ignore_pagination NUMBER,
  plug_chart_font_size VARCHAR2(255 BYTE),
  plug_chart_max_rows NUMBER,
  plug_chart_num_mask VARCHAR2(255 BYTE),
  plug_chart_scale VARCHAR2(255 BYTE),
  plug_chart_axis VARCHAR2(255 BYTE),
  plug_chart_show_summary VARCHAR2(255 BYTE),
  report_total_text_format VARCHAR2(4000 BYTE),
  break_column_text_format VARCHAR2(4000 BYTE),
  break_before_row VARCHAR2(4000 BYTE),
  break_generic_column VARCHAR2(4000 BYTE),
  break_after_row VARCHAR2(4000 BYTE),
  break_type_flag VARCHAR2(255 BYTE) CONSTRAINT wwv_break_flag_cc CHECK (break_type_flag in (
                                'REPEAT_HEADINGS_ON_BREAK_1',
                                'DEFAULT_BREAK_FORMATTING')),
  break_repeat_heading_format VARCHAR2(4000 BYTE),
  csv_output VARCHAR2(1 BYTE) CONSTRAINT wwv_csv_output_flag_ck CHECK (csv_output in ('Y','N')),
  csv_output_link_text VARCHAR2(4000 BYTE),
  print_url VARCHAR2(4000 BYTE),
  print_url_label VARCHAR2(4000 BYTE),
  prn_output VARCHAR2(1 BYTE) CONSTRAINT plug_prn_output CHECK (prn_output in ('Y','N')),
  prn_print_server_overwrite VARCHAR2(4000 BYTE),
  prn_template_id NUMBER,
  prn_format VARCHAR2(255 BYTE) CONSTRAINT plug_prn_format CHECK (prn_format in (
                                          'PDF',
                                          'RTF',
                                          'XLS',
                                          'HTM',
                                          'XML'
                                      )),
  prn_format_item VARCHAR2(4000 BYTE),
  prn_output_show_link VARCHAR2(1 BYTE) CONSTRAINT plug_prn_show_link CHECK (prn_output_show_link in ('Y','N')),
  prn_output_link_text VARCHAR2(4000 BYTE),
  prn_output_file_name VARCHAR2(4000 BYTE),
  prn_content_disposition VARCHAR2(255 BYTE) CONSTRAINT plug_prn_content_disp CHECK (prn_content_disposition in (
                                         'INLINE',
                                         'ATTACHMENT'
                                     )),
  prn_document_header VARCHAR2(255 BYTE) CONSTRAINT plug_prn_doc_header CHECK (prn_document_header in (
                                         'SERVER',
                                         'APEX'
                                     )),
  prn_units VARCHAR2(4000 BYTE) CONSTRAINT plug_prn_units CHECK (prn_units in (
                                         'POINTS',
                                         'INCHES',
                                         'MILLIMETERS',
                                         'CENTIMETERS'
                                     )),
  prn_paper_size VARCHAR2(4000 BYTE) CONSTRAINT plug_prn_paper_size CHECK (prn_paper_size in (
                                        'CUSTOM',
                                        'LETTER',
                                        'LEGAL',
                                        'TABLOID',
                                        'A4',
                                        'A3'
                                     )),
  prn_width_units VARCHAR2(255 BYTE) CONSTRAINT plug_prn_width_units CHECK (prn_width_units in (
                                         'PERCENTAGE',
                                         'POINTS'
                                     )),
  prn_width NUMBER,
  prn_height NUMBER,
  prn_orientation VARCHAR2(4000 BYTE) CONSTRAINT plug_prn_orientation CHECK (prn_orientation in (
                                         'HORIZONTAL',
                                         'VERTICAL'
                                     )),
  prn_page_header VARCHAR2(4000 BYTE),
  prn_page_header_alignment VARCHAR2(255 BYTE) CONSTRAINT plug_prn_header_align CHECK (prn_page_header_alignment in ('LEFT','CENTER','RIGHT')),
  prn_page_header_font_color VARCHAR2(4000 BYTE),
  prn_page_header_font_family VARCHAR2(4000 BYTE),
  prn_page_header_font_weight VARCHAR2(4000 BYTE),
  prn_page_header_font_size VARCHAR2(4000 BYTE),
  prn_page_footer VARCHAR2(4000 BYTE),
  prn_page_footer_alignment VARCHAR2(255 BYTE) CONSTRAINT plug_prn_footer_align CHECK (prn_page_footer_alignment in ('LEFT','CENTER','RIGHT')),
  prn_page_footer_font_color VARCHAR2(4000 BYTE),
  prn_page_footer_font_family VARCHAR2(4000 BYTE),
  prn_page_footer_font_weight VARCHAR2(4000 BYTE),
  prn_page_footer_font_size VARCHAR2(4000 BYTE),
  prn_header_bg_color VARCHAR2(4000 BYTE),
  prn_header_font_color VARCHAR2(4000 BYTE),
  prn_header_font_family VARCHAR2(4000 BYTE),
  prn_header_font_weight VARCHAR2(4000 BYTE),
  prn_header_font_size VARCHAR2(4000 BYTE),
  prn_body_bg_color VARCHAR2(4000 BYTE),
  prn_body_font_color VARCHAR2(4000 BYTE),
  prn_body_font_family VARCHAR2(4000 BYTE),
  prn_body_font_weight VARCHAR2(4000 BYTE),
  prn_body_font_size VARCHAR2(4000 BYTE),
  prn_border_color VARCHAR2(4000 BYTE),
  prn_border_width NUMBER,
  shared_query_id NUMBER,
  translate_title VARCHAR2(1 BYTE) CONSTRAINT wwv_translate_title_ck CHECK (translate_title in ('Y','N')),
  security_group_id NUMBER NOT NULL,
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  plug_comment VARCHAR2(4000 BYTE),
  use_custom_item_layout VARCHAR2(1 BYTE),
  custom_item_layout CLOB,
  sort_null VARCHAR2(1 BYTE) CONSTRAINT wwv_pp_sort_null_ck CHECK (sort_null in (null,'F','L')),
  region_attributes_substitution VARCHAR2(4000 BYTE),
  report_attributes_substitution VARCHAR2(4000 BYTE),
  std_rpt_max_query_cost NUMBER,
  java_entry_point VARCHAR2(255 BYTE),
  plug_create_link_text VARCHAR2(4000 BYTE),
  plug_create_link_target VARCHAR2(4000 BYTE),
  plug_create_image VARCHAR2(4000 BYTE),
  plug_create_image_attributes VARCHAR2(4000 BYTE),
  plug_edit_link_text VARCHAR2(4000 BYTE),
  plug_edit_link_target VARCHAR2(4000 BYTE),
  plug_edit_image VARCHAR2(4000 BYTE),
  plug_edit_image_attributes VARCHAR2(4000 BYTE),
  plug_expand_link_text VARCHAR2(4000 BYTE),
  plug_expand_link_target VARCHAR2(4000 BYTE),
  plug_expand_image VARCHAR2(4000 BYTE),
  plug_expand_image_attributes VARCHAR2(4000 BYTE),
  plug_close_link_text VARCHAR2(4000 BYTE),
  plug_close_link_target VARCHAR2(4000 BYTE),
  plug_close_image VARCHAR2(4000 BYTE),
  plug_close_image_attributes VARCHAR2(4000 BYTE),
  CONSTRAINT wwv_flow_page_plugs_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_plug_to_flow_fk FOREIGN KEY (flow_id) REFERENCES apex_030200.wwv_flows ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_flow_plug_to_page_fk FOREIGN KEY (flow_id,page_id) REFERENCES apex_030200.wwv_flow_steps (flow_id,"ID") ON DELETE CASCADE
);