CREATE TABLE apex_030200.wwv_flow_platform_pref (
  "ID" NUMBER NOT NULL,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  "VALUE" VARCHAR2(4000 BYTE) NOT NULL,
  PRIMARY KEY ("ID"),
  UNIQUE ("NAME")
);