CREATE TABLE apex_030200.wwv_flow_provision_company (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  company_name VARCHAR2(255 BYTE) NOT NULL,
  admin_first_name VARCHAR2(255 BYTE),
  admin_last_name VARCHAR2(255 BYTE),
  admin_title VARCHAR2(255 BYTE),
  admin_email VARCHAR2(255 BYTE),
  admin_phone VARCHAR2(255 BYTE),
  admin_id NUMBER,
  admin_userid VARCHAR2(255 BYTE) NOT NULL,
  company_address VARCHAR2(255 BYTE),
  city VARCHAR2(255 BYTE),
  "STATE" VARCHAR2(255 BYTE),
  zip VARCHAR2(255 BYTE),
  country VARCHAR2(30 BYTE),
  company_type VARCHAR2(255 BYTE),
  company_website VARCHAR2(255 BYTE),
  number_of_employees VARCHAR2(255 BYTE),
  company_phone VARCHAR2(255 BYTE),
  company_fax VARCHAR2(255 BYTE),
  oracle_partner VARCHAR2(255 BYTE) CHECK (oracle_partner in ('YES','NO')),
  how_did_you_hear_about_us VARCHAR2(255 BYTE),
  service_use_status VARCHAR2(30 BYTE) CHECK (service_use_status in ('FULL_USE','TRIAL')),
  database_size NUMBER,
  service_start_date DATE,
  service_termination_date DATE,
  schema_name VARCHAR2(255 BYTE) NOT NULL,
  estimated_end_users NUMBER,
  page_views_per_day NUMBER,
  project_description VARCHAR2(4000 BYTE),
  project_justification VARCHAR2(4000 BYTE),
  project_approval_date DATE,
  project_actual_begin_date DATE,
  project_actual_end_date DATE,
  project_status VARCHAR2(255 BYTE) CONSTRAINT ck_flow_prov_proj_status CHECK (project_status in (
                                 'IN_PROGRESS',
                                 'REQUESTED',
                                 'ACCEPTED',
                                 'DECLINED',
                                 'APPROVED',
                                 'TERMINATION_IN_PROGRESS',
                                 'TERMINATION_IN_PROGRESS2',
                                 'TERMINATION_IN_PROGRESS3',
                                 'TERMINATION_IN_PROGRESS4',
                                 'TERMINATION_IN_PROGRESS5',
                                 'TERMINATION_IN_PROGRESS6',
                                 'TERMINATED')),
  work_log VARCHAR2(4000 BYTE),
  request_date DATE,
  CONSTRAINT pk_flow_prov_project_id PRIMARY KEY ("ID")
);