CREATE TABLE apex_030200.wwv_mig_frm_windows (
  "ID" NUMBER NOT NULL,
  formmodule_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  "NAME" VARCHAR2(4000 BYTE),
  window_comment CLOB,
  title VARCHAR2(4000 BYTE),
  height VARCHAR2(4000 BYTE),
  width VARCHAR2(4000 BYTE),
  resizeallowed VARCHAR2(4000 BYTE) DEFAULT 'false',
  visualattributename VARCHAR2(4000 BYTE),
  modal VARCHAR2(4000 BYTE) DEFAULT 'false',
  hideonexit VARCHAR2(4000 BYTE) DEFAULT 'false',
  windowstyle VARCHAR2(4000 BYTE),
  maximizeallowed VARCHAR2(4000 BYTE) DEFAULT 'false',
  minimizeallowed VARCHAR2(4000 BYTE) DEFAULT 'false',
  dirtyinfo VARCHAR2(4000 BYTE),
  primarycanvas VARCHAR2(4000 BYTE),
  parenttype VARCHAR2(4000 BYTE),
  parentname VARCHAR2(4000 BYTE),
  parentmodule VARCHAR2(4000 BYTE),
  parentmoduletype VARCHAR2(4000 BYTE),
  showverticalscrollbar VARCHAR2(4000 BYTE),
  showhorizontalscrollbar VARCHAR2(4000 BYTE),
  minimizetitle VARCHAR2(4000 BYTE),
  moveallowed VARCHAR2(4000 BYTE),
  horizontaltoolbarcanvasname VARCHAR2(4000 BYTE),
  xposition VARCHAR2(4000 BYTE),
  yposition VARCHAR2(4000 BYTE),
  iconfilename VARCHAR2(4000 BYTE),
  clearallowed VARCHAR2(4000 BYTE),
  backcolor VARCHAR2(4000 BYTE),
  bevel VARCHAR2(4000 BYTE),
  fillpattern VARCHAR2(4000 BYTE),
  fontname VARCHAR2(4000 BYTE),
  fontsize VARCHAR2(4000 BYTE),
  fontspacing VARCHAR2(4000 BYTE),
  fontstyle VARCHAR2(4000 BYTE),
  fontweight VARCHAR2(4000 BYTE),
  foregroundcolor VARCHAR2(4000 BYTE),
  helpbooktopic VARCHAR2(4000 BYTE),
  inheritmenu VARCHAR2(4000 BYTE) DEFAULT 'false',
  languagedirection VARCHAR2(4000 BYTE),
  parentfilename VARCHAR2(4000 BYTE),
  parentfilepath VARCHAR2(4000 BYTE),
  persistentclientinfolength VARCHAR2(4000 BYTE),
  smartclass VARCHAR2(4000 BYTE) DEFAULT 'false',
  subclassobjectgroup VARCHAR2(4000 BYTE) DEFAULT 'false',
  verticaltoolbarcanvasname VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CONSTRAINT wwv_mig_frm_window_sel_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_frm_window_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_frm_wndow_frmmdl_id_fk FOREIGN KEY (formmodule_id) REFERENCES apex_030200.wwv_mig_frm_formmodules ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_frm_wndow_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);