CREATE TABLE apex_030200.wwv_flow_worksheet_rpts (
  "ID" NUMBER NOT NULL,
  worksheet_id NUMBER NOT NULL,
  flow_id NUMBER NOT NULL,
  page_id NUMBER NOT NULL,
  session_id NUMBER,
  base_report_id NUMBER,
  application_user VARCHAR2(255 BYTE),
  "NAME" VARCHAR2(255 BYTE),
  description VARCHAR2(4000 BYTE),
  report_seq NUMBER NOT NULL,
  report_type VARCHAR2(255 BYTE),
  status VARCHAR2(30 BYTE) CONSTRAINT wwv_flow_ws_rpt_status_ck CHECK (status in (
                           'PRIVATE',
                           'PUBLIC')),
  category_id NUMBER,
  autosave VARCHAR2(1 BYTE),
  is_default VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_ws_rpt_def_ck CHECK (is_default in (
                           'Y',
                           'N')),
  display_rows NUMBER,
  pagination_min_row NUMBER,
  report_columns VARCHAR2(4000 BYTE),
  sort_column_1 VARCHAR2(255 BYTE),
  sort_direction_1 VARCHAR2(255 BYTE),
  sort_column_2 VARCHAR2(255 BYTE),
  sort_direction_2 VARCHAR2(255 BYTE),
  sort_column_3 VARCHAR2(255 BYTE),
  sort_direction_3 VARCHAR2(255 BYTE),
  sort_column_4 VARCHAR2(255 BYTE),
  sort_direction_4 VARCHAR2(255 BYTE),
  sort_column_5 VARCHAR2(255 BYTE),
  sort_direction_5 VARCHAR2(255 BYTE),
  sort_column_6 VARCHAR2(255 BYTE),
  sort_direction_6 VARCHAR2(255 BYTE),
  break_on VARCHAR2(4000 BYTE),
  break_enabled_on VARCHAR2(4000 BYTE),
  control_break_options VARCHAR2(255 BYTE),
  sum_columns_on_break VARCHAR2(4000 BYTE),
  avg_columns_on_break VARCHAR2(4000 BYTE),
  max_columns_on_break VARCHAR2(4000 BYTE),
  min_columns_on_break VARCHAR2(4000 BYTE),
  median_columns_on_break VARCHAR2(4000 BYTE),
  mode_columns_on_break VARCHAR2(4000 BYTE),
  count_columns_on_break VARCHAR2(4000 BYTE),
  flashback_mins_ago VARCHAR2(255 BYTE),
  flashback_enabled VARCHAR2(1 BYTE) NOT NULL CONSTRAINT wwv_flow_ws_rpt_fb_ck CHECK (flashback_enabled in (
                           'Y',
                           'N')),
  chart_type VARCHAR2(255 BYTE),
  chart_3d VARCHAR2(1 BYTE),
  chart_label_column VARCHAR2(255 BYTE),
  chart_label_title VARCHAR2(255 BYTE),
  chart_value_column VARCHAR2(255 BYTE),
  chart_aggregate VARCHAR2(255 BYTE),
  chart_value_title VARCHAR2(255 BYTE),
  chart_sorting VARCHAR2(30 BYTE) CONSTRAINT wwv_flow_ws_rpt_chrt_ck CHECK (chart_sorting in (
                           'DEFAULT',
                           'VALUE_DESC',
                           'VALUE_ASC',
                           'LABEL_DESC',
                           'LABEL_ASC')),
  calendar_date_column VARCHAR2(255 BYTE),
  calendar_display_column VARCHAR2(255 BYTE),
  created_on DATE NOT NULL,
  created_by VARCHAR2(255 BYTE) NOT NULL,
  updated_on DATE,
  updated_by VARCHAR2(255 BYTE),
  security_group_id NUMBER NOT NULL,
  CONSTRAINT wwv_flow_worksheet_rpts_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flow_worksheet_rpts_fk FOREIGN KEY (category_id) REFERENCES apex_030200.wwv_flow_worksheet_categories ("ID"),
  CONSTRAINT wwv_flow_worksheet_rpts_fk2 FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);