CREATE TABLE apex_030200.wwv_mig_olb_objectlibrarytab (
  "ID" NUMBER NOT NULL,
  objectlibrary_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  "NAME" VARCHAR2(4000 BYTE),
  objectcount VARCHAR2(4000 BYTE),
  "LABEL" VARCHAR2(4000 BYTE),
  dirtyinfo VARCHAR2(4000 BYTE),
  persistentclientinfolength VARCHAR2(4000 BYTE),
  objectlibrarytab_comment CLOB,
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL CONSTRAINT wwv_mig_olb_olt_sel_for_app CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_olb_objlibtab_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_olb_olt_objlib_id_fk FOREIGN KEY (objectlibrary_id) REFERENCES apex_030200.wwv_mig_olb_objectlibrary ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_olb_olt_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);