CREATE TABLE apex_030200.wwv_flows (
  "ID" NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  global_id NUMBER,
  "ALIAS" VARCHAR2(255 BYTE) NOT NULL,
  display_id NUMBER,
  "OWNER" VARCHAR2(30 BYTE) NOT NULL,
  "NAME" VARCHAR2(255 BYTE) NOT NULL,
  default_page_template NUMBER,
  home_link VARCHAR2(2000 BYTE),
  box_width VARCHAR2(30 BYTE),
  webdb_logging VARCHAR2(30 BYTE) CONSTRAINT wwv_valid_flow_loggingyesno CHECK (webdb_logging in (
                                  'YES',
                                  'NO')),
  printer_friendly_template NUMBER,
  default_region_template NUMBER,
  default_label_template NUMBER,
  default_report_template NUMBER,
  default_list_template NUMBER,
  default_menu_template NUMBER,
  default_button_template NUMBER,
  default_calendar_template NUMBER,
  error_template NUMBER,
  flow_language VARCHAR2(255 BYTE),
  flow_language_derived_from VARCHAR2(30 BYTE) CONSTRAINT wwv_valid_flow_lang_from CHECK (flow_language_derived_from in (
                                  'en-US', 'en-GB',
                                  'fr', 'es',
                                  'no', 'pt',
                                  'de', 'it',
                                  'bg', 'zh',
                                  'cs', 'da',
                                  'nl', 'fi',
                                  'fr-CA', 'fr-BE',
                                  'el', 'hu',
                                  'id', 'ga',
                                  'ja', 'ko',
                                  'pl', 'pt-BR',
                                  'ro', 'ru',
                                  'sr', 'sk',
                                  'sl', 'sv',
                                  'tr', 'uk',
                                  'FLOW_PRIMARY_LANGUAGE',
                                  'BROWSER',
                                  'ITEM_PREFERENCE',
                                  'FLOW_PREFERENCE',
                                  '0')),
  charset VARCHAR2(255 BYTE),
  media_type VARCHAR2(255 BYTE),
  date_format VARCHAR2(255 BYTE),
  flow_image_prefix VARCHAR2(255 BYTE),
  "AUTHENTICATION" VARCHAR2(255 BYTE) CONSTRAINT wwv_flow_valid_auth CHECK ("AUTHENTICATION" in (
                                  'DATABASE',
                                  'COOKIE',
                                  'ASFCOOKIE',
                                  'ORACLE_LOGIN_SERVER',
                                  'CUSTOM2',
                                  'CUSTOM')),
  login_url VARCHAR2(2000 BYTE),
  logout_url VARCHAR2(2000 BYTE),
  max_session_length_sec NUMBER,
  on_max_session_timeout_url VARCHAR2(4000 BYTE),
  max_session_idle_sec NUMBER,
  on_max_idle_timeout_url VARCHAR2(4000 BYTE),
  logo_image VARCHAR2(500 BYTE),
  logo_image_attributes VARCHAR2(4000 BYTE),
  public_url_prefix VARCHAR2(255 BYTE),
  public_user VARCHAR2(255 BYTE),
  dbauth_url_prefix VARCHAR2(255 BYTE),
  proxy_server VARCHAR2(255 BYTE),
  custom_authentication_process VARCHAR2(4000 BYTE),
  custom_authentication_page VARCHAR2(255 BYTE),
  custom_auth_login_url VARCHAR2(4000 BYTE),
  flow_version VARCHAR2(255 BYTE),
  flow_status VARCHAR2(30 BYTE) CONSTRAINT wwv_flow_valid_status CHECK (flow_status in (
                                  'AVAILABLE',
                                  'AVAILABLE_W_EDIT_LINK',
                                  'AVAILABLE_W_INLINE_EDIT',
                                  'DEVELOPERS_ONLY',
                                  'UNAVAILABLE_URL',
                                  'UNAVAILABLE_PLSQL',
                                  'RESTRICTED_ACCESS',
                                  'UNAVAILABLE')),
  flow_unavailable_text VARCHAR2(4000 BYTE),
  restrict_to_user_list VARCHAR2(4000 BYTE),
  application_tab_set NUMBER,
  exact_substitutions_only VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_exact_subs_flag CHECK (exact_substitutions_only in ('Y','N')),
  csv_encoding VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_csv_encoding CHECK (csv_encoding in (
                                  'Y',
                                  'N')),
  build_status VARCHAR2(30 BYTE) CONSTRAINT wwv_flow_valid_build_status CHECK (build_status in (
                                  'RUN_AND_BUILD',
                                  'RUN_ONLY')),
  vpd VARCHAR2(4000 BYTE),
  security_scheme VARCHAR2(255 BYTE),
  rejoin_existing_sessions VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_valid_rejoin_es CHECK (rejoin_existing_sessions in (
                                  'Y',
                                  'N')),
  checksum_salt RAW(255),
  checksum_salt_last_reset DATE,
  substitution_string_01 VARCHAR2(255 BYTE),
  substitution_value_01 VARCHAR2(4000 BYTE),
  substitution_string_02 VARCHAR2(255 BYTE),
  substitution_value_02 VARCHAR2(4000 BYTE),
  substitution_string_03 VARCHAR2(255 BYTE),
  substitution_value_03 VARCHAR2(4000 BYTE),
  substitution_string_04 VARCHAR2(255 BYTE),
  substitution_value_04 VARCHAR2(4000 BYTE),
  substitution_string_05 VARCHAR2(255 BYTE),
  substitution_value_05 VARCHAR2(4000 BYTE),
  substitution_string_06 VARCHAR2(255 BYTE),
  substitution_value_06 VARCHAR2(4000 BYTE),
  substitution_string_07 VARCHAR2(255 BYTE),
  substitution_value_07 VARCHAR2(4000 BYTE),
  substitution_string_08 VARCHAR2(255 BYTE),
  substitution_value_08 VARCHAR2(4000 BYTE),
  substitution_string_09 VARCHAR2(255 BYTE),
  substitution_value_09 VARCHAR2(4000 BYTE),
  substitution_string_10 VARCHAR2(255 BYTE),
  substitution_value_10 VARCHAR2(4000 BYTE),
  substitution_string_11 VARCHAR2(255 BYTE),
  substitution_value_11 VARCHAR2(4000 BYTE),
  substitution_string_12 VARCHAR2(255 BYTE),
  substitution_value_12 VARCHAR2(4000 BYTE),
  substitution_string_13 VARCHAR2(255 BYTE),
  substitution_value_13 VARCHAR2(4000 BYTE),
  substitution_string_14 VARCHAR2(255 BYTE),
  substitution_value_14 VARCHAR2(4000 BYTE),
  substitution_string_15 VARCHAR2(255 BYTE),
  substitution_value_15 VARCHAR2(4000 BYTE),
  substitution_string_16 VARCHAR2(255 BYTE),
  substitution_value_16 VARCHAR2(4000 BYTE),
  substitution_string_17 VARCHAR2(255 BYTE),
  substitution_value_17 VARCHAR2(4000 BYTE),
  substitution_string_18 VARCHAR2(255 BYTE),
  substitution_value_18 VARCHAR2(4000 BYTE),
  substitution_string_19 VARCHAR2(255 BYTE),
  substitution_value_19 VARCHAR2(4000 BYTE),
  substitution_string_20 VARCHAR2(255 BYTE),
  substitution_value_20 VARCHAR2(4000 BYTE),
  last_updated_by VARCHAR2(255 BYTE),
  last_updated_on DATE,
  default_chart_template NUMBER,
  default_reportr_template NUMBER,
  default_form_template NUMBER,
  default_wizard_template NUMBER,
  default_tabform_template NUMBER,
  default_menur_template NUMBER,
  default_listr_template NUMBER,
  theme_id NUMBER,
  "GROUP_ID" NUMBER,
  global_notification VARCHAR2(4000 BYTE),
  page_protection_enabled_y_n VARCHAR2(1 BYTE) CONSTRAINT wwv_flow_page_prot_enable_flag CHECK (page_protection_enabled_y_n in ('Y','N')),
  CONSTRAINT wwv_flow_flow_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_flows_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);