CREATE TABLE apex_030200.wwv_flow_languages (
  "ID" NUMBER NOT NULL,
  lang_id VARCHAR2(255 BYTE) NOT NULL,
  lang_id_upper VARCHAR2(255 BYTE) NOT NULL,
  lang_name VARCHAR2(255 BYTE) NOT NULL,
  "NLS_LANGUAGE" VARCHAR2(255 BYTE) NOT NULL,
  "NLS_TERRITORY" VARCHAR2(255 BYTE),
  "NLS_SORT" VARCHAR2(255 BYTE),
  nls_windows_charset VARCHAR2(255 BYTE),
  CONSTRAINT wwv_flow_languages_pk PRIMARY KEY ("ID")
);