CREATE TABLE apex_030200.wwv_mig_olb_t_tp_gggg_cpdtxt (
  "ID" NUMBER NOT NULL,
  graphics_id NUMBER NOT NULL,
  security_group_id NUMBER NOT NULL,
  "NAME" VARCHAR2(4000 BYTE),
  subclasssubobject VARCHAR2(4000 BYTE),
  dirtyinfo VARCHAR2(4000 BYTE),
  select_for_app VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL CONSTRAINT wwv_mig_olb_ttpggggct_sfa CHECK (select_for_app in ('Y', 'N')),
  applicable VARCHAR2(1 BYTE) DEFAULT 'Y',
  "COMPLETE" VARCHAR2(1 BYTE) DEFAULT 'N',
  "PRIORITY" NUMBER(1) DEFAULT 3,
  assignee VARCHAR2(255 BYTE),
  notes VARCHAR2(4000 BYTE),
  tags VARCHAR2(4000 BYTE),
  created_on DATE,
  created_by VARCHAR2(400 BYTE),
  last_updated_on DATE,
  last_updated_by VARCHAR2(400 BYTE),
  CONSTRAINT wwv_mig_olb_t_tp_gggg_ct_pk PRIMARY KEY ("ID"),
  CONSTRAINT wwv_mig_olb_ttpggggct_g_id_fk FOREIGN KEY (graphics_id) REFERENCES apex_030200.wwv_mig_olb_t_tp_ggg_graphics ("ID") ON DELETE CASCADE,
  CONSTRAINT wwv_mig_olb_ttpggggct_sg_id_fk FOREIGN KEY (security_group_id) REFERENCES apex_030200.wwv_flow_companies (provisioning_company_id) ON DELETE CASCADE
);